apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
          -name: springboot
          image: jayuser/helloworld:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: PORT
              value: "8090"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: helloworld